# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glad_config = debug
  Rendeer_config = debug
endif
ifeq ($(config),release)
  glad_config = release
  Rendeer_config = release
endif

PROJECTS := glad Rendeer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C external/glad -f Makefile config=$(glad_config)
endif

Rendeer: glad
ifneq (,$(Rendeer_config))
	@echo "==== Building Rendeer ($(Rendeer_config)) ===="
	@${MAKE} --no-print-directory -C Rendeer -f Makefile config=$(Rendeer_config)
endif

clean:
	@${MAKE} --no-print-directory -C external/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Rendeer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glad"
	@echo "   Rendeer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"